Find the symmetry matrices of a space group starting from a list of generators

In [1]:
# Pseudocode:

#find_sym_matrices(knowMatrices, *newMatrices)
#    for matrix_i in newMatrices
#        for matrix_j in knownMatrices
#            if matrix_i x matrix_j = newMatrix then
#                if newMatrix is not the identity matrix then
#                     knownMatrices.append(newMatrix)
#                     find_sym_matrices(knownMatrices, newMatrices)
#            else
                 #no new matrices
#   print knownMatrices

In [1]:
import numpy as np

In [7]:
def is(knownMatrices, *args):
    
    foundNewOne = False
    newMatrices = []
    
    if args: 
        matrixToMultiply = args[0]
    else:
        # remember python passees objects by reference!
        # so need to shallow copy lists
        matrixToMultiply =knownMatrices[:]
        
    startingSet = knownMatrices[:] 
   

    for matrix_i in matrixToMultiply:
        for matrix_j in startingSet:
    
            isThisNew = np.dot(matrix_i, matrix_j)
            print
            print "isthisnew"
            print isThisNew
 
            #assume
            new = True
            
            if np.array_equal(isThisNew, np.identity(3)):
                new = False
                print "identity matrix"
                
            else:    
                for matrix in knownMatrices:
                    #look if we already have it
                    if np.array_equal(isThisNew, matrix):
                        #not a new matrix
                        print "not new"
                        new = False
                        break #stop looking                       
                    

                  
            if new is True:
                #finally new matrix
                foundNewOne = True
                print "new"
                newMatrix = isThisNew
                newMatrices.append(newMatrix)
                knownMatrices.append(newMatrix)

                    
                        
    if foundNewOne:
        #multiply the new matrices with the rest of the set
        print "new Matrices", len(newMatrices)
        find_sym_matrices(knownMatrices, newMatrices)                

            
    return knownMatrices    


In [8]:
# For wurtsite the generators are
D_a = np.matrix([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])

D_b = np.matrix([[-1., 0., 0.], [0., -1., 0.], [0., 0., 1.]])
D_k = np.matrix([[0., -1., 0.], [-1., 0., 0.], [0., 0., 1.]])
D_n = np.matrix([[0., -1., 0.], [1., -1., 0.], [0., 0., 1.]])

wurtziteGen = [D_b, D_k, D_n]
mat = find_sym_matrices(wurtziteGen)



isthisnew
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity matrix

isthisnew
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
new

isthisnew
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]
new

isthisnew
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
not new

isthisnew
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity matrix

isthisnew
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
new

isthisnew
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]
not new

isthisnew
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
new

isthisnew
[[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
new
new Matrices 5

isthisnew
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
not new

isthisnew
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
not new

isthisnew
[[ 1. -1.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
new

isthisnew
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity matrix

isthisnew
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
not new

isthisnew
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]
not new

isthisnew
[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]

In [9]:
print "Wurtzite symmetry matrices are:"
for m in mat:
    print m
    print

Wurtzite symmetry matrices are:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]

[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]

[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]

[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]

[[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]

[[ 1. -1.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]

[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

[[-1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]

